name: device_details_flutter_module
description: Flutter module for device details viewer (Add-to-App example)
version: 0.1.0
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  device_details_flutter_plugin:
    path: ../shared/device_details_flutter_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  module:
    androidPackage: com.example.device_details_flutter_module
    iosBundleIdentifier: com.example.deviceDetailsFlutterModule
